### PR TITLE
Create it.json

### PR DESCRIPTION
**Pull request by ErikDW1**
Add Italian translation.

### CODE REVIEW

**Comment by JuTiger-Lee** [comment]
Thanks.

**Comment by ErikDW1** [comment]
When will this be available as update?

**Comment by JuTiger-Lee** [comment]
We will update to version 1.03 within this week.

**Comment by JuTiger-Lee** [comment]
updated. Thanks for your help with my project.

**Comment by ErikDW1** [comment]
You're welcome! Thanks for making this useful plugin!
If you need I'm eager to help.

**Pull request merged**
